version: '3.9'

services:

  go-app:
    build: ./app
    container_name: go-app
    volumes:
      - ./logs:/var/log

  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit
    volumes:
      - ./logs:/var/log
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
      - ./fluent-bit/state:/fluent-bit/state
    depends_on:
      - middleware-agent


  middleware-agent:
    image: ghcr.io/middleware-labs/mw-host-agent:master
    container_name: middleware-agent
    environment:
      MW_API_KEY: mepdhufxsqkmxuhqqaveqtbdygrnqoofwpif
      MW_TARGET: https://amuby.middleware.io:443
    ports:
      - "8006:8006"
